var num = 113;
var prime = 71;
var num1 = 21.241;
var num2 = 32e+10;
var num3 = 10;
var num4 = 10;
// let num5: number = "javascript";
// let num6: number = null;
// let string: string = num5;
console.log(prime);
console.log(num);
console.log(num1);
console.log(num2);
console.log(num3 + num4);
